services:
    postgres:
        image: postgres:latest
        container_name: twitter-postgres
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - twitter_db_volume:/var/lib/postgresql/data
        restart: always

volumes:
    twitter_db_volume:
        name: twitter_db_volume
