services:
    postgres:
        image: postgres:latest
        container_name: rastro-postgres
        env_file: ./server/.env
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: backend.Dockerfile
        container_name: rastro-backend
        env_file: ./server/.env
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        restart: always
        depends_on:
            postgres:
                condition: service_healthy

    frontend:
        build:
            context: .
            dockerfile: frontend.Dockerfile
            args:
                - VITE_API_URL=/api/
        container_name: rastro-frontend
        ports:
            - "80:80"
        restart: always
        depends_on:
            - backend

volumes:
    postgres_data:
