databases:
    - name: twitter-db
      databaseName: twitter_db
      user: twitter_user
      region: oregon

services:
    - type: web
      name: twitter-api
      runtime: python
      region: oregon
      buildCommand: |
          cd server
          pip install poetry
          poetry install
          python manage.py migrate
          python manage.py collectstatic --noinput
          python manage.py runseed
      startCommand: |
          cd server
          gunicorn twitter_api.wsgi:application --bind 0.0.0.0:$PORT
      envVars:
          - key: POSTGRES_HOST
            fromDatabase:
                name: twitter-db
                property: host
          - key: POSTGRES_PORT
            fromDatabase:
                name: twitter-db
                property: port
          - key: POSTGRES_DB
            fromDatabase:
                name: twitter-db
                property: database
          - key: POSTGRES_USER
            fromDatabase:
                name: twitter-db
                property: user
          - key: POSTGRES_PASSWORD
            fromDatabase:
                name: twitter-db
                property: password
          - key: DATABASE_URL
            fromDatabase:
                name: twitter-db
                property: connectionString
          - key: PYTHON_VERSION
            value: "3.13"
          - key: POETRY_VERSION
            value: "2.1.2"
          - key: DJANGO_SETTINGS_MODULE
            value: "twitter_api.settings"
          - key: PYTHONUNBUFFERED
            value: "1"

    - type: static
      name: twitter-client
      buildCommand: |
          cd client
          npm install -g pnpm
          pnpm install
          pnpm build
      staticPublishPath: ./client/dist
      headers:
          - path: /*
            name: X-Frame-Options
            value: SAMEORIGIN
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
      envVars:
          - key: NODE_VERSION
            value: "20"
