# Generated by Django 5.2.1 on 2025-05-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_alter_bio_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association_type', models.CharField(choices=[('retweet', 'Re-Tweet'), ('share', 'Share')], max_length=20)),
                ('associated_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_associations', to='twitter.tweet')),
                ('parent_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_associations', to='twitter.tweet')),
            ],
            options={
                'unique_together': {('parent_tweet', 'associated_tweet', 'association_type')},
            },
        ),
    ]
