name: Deploy para a máquina virtual

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    deploy:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

        name: Deploy para a máquina virtual
        runs-on: self-hosted
        steps:
            - name: Checkout do repositório
              uses: actions/checkout@v4

            - name: Rodar o script de deploy
              run: ./deploy.sh
