name: Docker Setup Test

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test-docker:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout do código
              uses: actions/checkout@v3

            - name: Configurar docker
              uses: docker/setup-buildx-action@v3

            - name: Instalando Docker Compose
              run: |
                  sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                  sudo chmod +x /usr/local/bin/docker-compose
                  docker-compose --version

            - name: Configurar arquivo.env
              run: |
                  cat > .env << EOF
                  POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
                  POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
                  POSTGRES_DB=${{ secrets.POSTGRES_DB }}
                  POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_DB_TEST=${{ secrets.POSTGRES_DB_TEST }}
                  EOF

            - name: Rodando o Docker compose
              run: |
                  echo "Executando o docker compose..."
                  docker-compose -f docker-compose-full.yml up -d
                  echo "Processo pronto! Docker compose está rodando."
              continue-on-error: true

            - name: Verificando os containers
              run: |
                  echo "Verificando os containers..."
                  docker ps -a
